Repository nanoframework/lib-Windows.Devices.I2c, pull requests merged in 2018-11, with the labels that each got.

#31 Add lazy initialization to I2cController
  source/Windows.Devices.I2c/I2cController.cs
  source/Windows.Devices.I2c/I2cDevice.cs
Labels: Type: enhancement

#33 Fix issue with I2C NativeInit and Dispose
  source/Windows.Devices.I2c/I2cDevice.cs
Labels: Type: bug

#35 Work CD-CI
  appveyor.yml
  install-7zip.ps1
  install-nf-build-components.ps1
Labels: Area: Config-and-Build

#36 Rework I2cController and I2cDevice
  source/Windows.Devices.I2c/I2cConnectionSettings.cs
  source/Windows.Devices.I2c/I2cController.cs
  source/Windows.Devices.I2c/I2cControllerManager.cs
  source/Windows.Devices.I2c/I2cDevice.cs
  source/Windows.Devices.I2c/I2cTransferResult.cs
  source/Windows.Devices.I2c/Windows.Devices.I2c.nfproj
Labels: Type: enhancement
